# tasks.yaml (FINAL - With Explicit Strategy Reasoning)

route_user_query:
  description: "Analyze the user's query: '{query}'. Classify it as 'ticker_specific_analysis', 'market_screening', or 'general_qa'."
  expected_output: "A JSON object with a 'route' key and an 'extracted_info' key (e.g., {{\"route\": \"ticker_specific_analysis\", \"extracted_info\": \"TSLA\"}})."

analyze_fundamentals:
  description: "Conduct a comprehensive fundamental analysis for {ticker}, using the 'Get Company Overview & Fundamentals' tool."
  expected_output: "A report on the company's fundamentals, including key metrics and a financial health assessment."

analyze_technical_indicators:
  description: "Conduct a detailed technical analysis for {ticker} using the 'Get Premium Technical Indicators' tool. You must interpret all the provided indicators (RSI, MACD, SMAs, Bollinger Bands)."
  expected_output: "A detailed technical report interpreting each indicator and providing an overall technical outlook (e.g., Bullish, Bearish, Neutral)."

develop_trading_strategy:
  description: >
    Develop a detailed trading strategy for {ticker}. You MUST use the 'Get Daily Stock Price History' tool to get the last 100 days of price data.
    From the data, you must perform the following steps:
    1.  **Identify the Current Price:** State the most recent closing price from the data.
    2.  **Calculate Key Levels:**
        *   Calculate Support: Find the lowest 'low' price from the last 30 days of data.
        *   Calculate Resistance: Find the highest 'high' price from the last 30 days of data.
    3.  **Formulate Trade Plans:** Based *only* on the Support and Resistance levels you calculated, create a Long and Short trade plan.
        *   For the Long Plan, the entry should be slightly above the Current Price, the take profit near the Resistance, and the stop loss below the entry but above the Support.
        *   For the Short Plan, the entry should be slightly below the Current Price, the take profit near the Support, and the stop loss above the Resistance.
    4.  **Justify the Plan:** Write a brief sentence explaining the logic for your price levels, for example: "The long strategy aims to capture the upward movement towards the 30-day high, with a stop loss placed at a reasonable risk point."
  expected_output: >
    A structured report containing:
    - Current Price: The most recent closing price.
    - Support Level: The calculated support price.
    - Resistance Level: The calculated resistance price.
    - Justification: A brief explanation for the strategy.
    - A detailed Long Trade Plan with Entry, Take Profit, and Stop Loss prices.
    - A detailed Short Trade Plan with Entry, Take Profit, and Stop Loss prices.

analyze_market_sentiment:
  description: "Investigate and summarize the market sentiment for {ticker}, using the 'Get News & Market Sentiment' tool."
  expected_output: "A concise sentiment analysis report, including overall sentiment and key news catalysts."

synthesize_trade_recommendation:
  description: >
    You are the Chief Investment Strategist. Your final task is to assemble a complete, professional investment report for {ticker}.
    The user's original query was: '{query}'.
    You have been given four reports: Fundamental Analysis, Technical Indicator Analysis, a Trading Strategy Plan, and a Market Sentiment Analysis.
    Your job is to synthesize all this information into a final report using the exact format specified in the 'expected_output'.
    You MUST extract the specific data points from the context reports to fill in every field. The confidence score should be your reasoned judgment (High, Medium, or Low) based on the alignment of all four reports, with a percentage to quantify it.
  expected_output: >
    A final, beautifully formatted investment advisory report for {ticker}.
    The report MUST start and end with "---" separators. Use proper Markdown.

    ---
    **Ticker:** {ticker}
    
    **Current Price:** $[Extract the 'Current Price' from the Trading Strategy Plan]
    
    **Recommendation:** [Buy | Sell | Hold]
    
    **Confidence:** [High | Medium | Low] ([Provide a numeric percentage in parenthesis, e.g., Medium (65%)])
    
    **Summary:**
    A concise paragraph explaining your reasoning. Start by stating if the stock is a good candidate for the user's query and why. Then, integrate the key fundamental, technical, and sentiment findings to justify your recommendation and confidence level.
    
    **Trading Strategy:**
    *   **Strategy Rationale:** [Extract the 'Justification' from the Trading Strategy Plan.]
    *   **Long Trade Plan:**
        *   Entry Price: $[Extract from Trading Strategy Plan]
        *   Take Profit: $[Extract from Trading STrategy Plan]
        *   Stop Loss: $[Extract from Trading Strategy Plan]
    *   **Short Trade Plan:**
        *   Entry Price: $[Extract from Trading Strategy Plan]
        *   Take Profit: $[Extract from Trading Strategy Plan]
        *   Stop Loss: $[Extract from Trading Strategy Plan]
    
    **Key Data Points:**
    *   **Fundamentals:** [A single bullet point summarizing the most critical finding from the Fundamental Analysis report.]
    *   **Technicals:** [A single bullet aummarizing the overall technical outlook from the Technical Indicator Analysis report.]
    *   **Sentiment:** [A single bullet point summarizing the most critical finding from the Market Sentiment Analysis report.]
    
    **Risks:**
    - [A bullet point list of key immediate risks to consider, based on all available reports (e.g., overbought RSI, high valuation, negative news).]
    ---

# --- Unchanged Screening Tasks ---
screen_market_for_tickers:
  description: "Based on the user's request for '{query}', use web search to identify promising stock tickers."
  expected_output: "A clean, comma-separated string of no more than 5 relevant stock ticker symbols. If none are found, return an empty string."

summarize_findings:
  description: "Review the collection of stock analyses provided in the context. The user's original request was: '{query}'. Write a final, top-level executive summary."
  expected_output: "A final, user-friendly executive summary that directly answers the user's query and introduces the detailed reports."