# tasks.yaml (FINAL - With Advanced Technical Task)

route_user_query:
  description: "Analyze the user's query: '{query}'. Classify it as 'ticker_specific_analysis', 'market_screening', or 'general_qa'."
  expected_output: "A JSON object with a 'route' key and an 'extracted_info' key."

# --- SCREENING FUNNEL TASKS ---
screen_market_for_tickers:
  description: "Use the 'Yahoo Finance Stock Screener' tool to generate a broad list of undervalued large-cap stocks. The user's original query was: '{query}'."
  expected_output: "A clean, comma-separated string of all stock ticker symbols found by the tool."

filter_and_select_candidates:
  description: >
    You have been given a broad list of stock tickers. The user's original query was: '{query}'.
    Your job is to filter this list down to the **top 2 or 3** most promising candidates that best match the user's qualitative criteria.
    For each stock in the list, perform a web search to find recent news, analyst opinions, or upcoming catalysts.
  expected_output: "A final, clean, comma-separated string of the 2-3 best ticker symbols."

# --- DETAILED ANALYSIS TASKS ---
analyze_fundamentals:
  description: "Conduct a comprehensive fundamental analysis for {ticker}, using the 'Get Company Overview & Fundamentals' tool."
  expected_output: "A report on the company's fundamentals, including key metrics and a financial health assessment."

analyze_advanced_technicals:
  description: >
    Your sole job is to use the 'Advanced Technical Analysis' tool for the stock ticker {ticker}.
    Then, present the JSON output from the tool in a clean, human-readable report.
    You must not add any interpretation of your own; your task is to simply call the tool and format its expert output.
  expected_output: >
    A perfectly formatted summary of the technical analysis, directly reflecting the tool's output. The report must include:
    - Latest Price
    - Trend Analysis (50-day SMA, 200-day SMA, Conclusion)
    - Momentum Analysis (RSI-14, Conclusion)
    - Volume Analysis (Latest Volume, 30-day Avg, Conclusion)
    - Volatility Analysis (ATR-14, Insight, Suggested Stop-Loss distance)
    - A final Expert Summary sentence as provided by the tool.

analyze_market_sentiment:
  description: "Investigate and summarize the market sentiment for {ticker}, using the 'Get News & Market Sentiment' tool."
  expected_output: "A concise sentiment analysis report, including overall sentiment and key news catalysts."

synthesize_trade_recommendation:
  description: >
    You are the Chief Investment Strategist. Your final task is to assemble a complete, professional investment report for {ticker}.
    The user's original query was: '{query}'.
    You have been given three expert reports: Fundamental Analysis, Advanced Technical Analysis, and Market Sentiment Analysis.
    Your job is to synthesize all this information into a final report using the exact format specified below.
    The 'Trading Strategy' section should be derived from the Advanced Technical Analysis report, using the latest price and the suggested stop-loss distance from the volatility analysis to calculate take-profit and stop-loss levels.
  expected_output: >
    A final, beautifully formatted investment advisory report.
    ---
    **Ticker:** {ticker}
    
    **Current Price:** $[Extract from the Advanced Technical Analysis report]
    
    **Recommendation:** [Buy | Sell | Hold]
    
    **Confidence:** [High | Medium | Low] ([Provide a numeric percentage, e.g., (75%)])
    
    **Summary:**
    A concise paragraph explaining your reasoning. Justify your recommendation by integrating the conclusions from the fundamental, technical, and sentiment reports.
    
    **Trading Strategy (Derived from Volatility Analysis):**
    *   **Strategy Rationale:** The following trade plans are based on the calculated average true range (ATR) to provide a risk-to-reward ratio of approximately 2:1.
    *   **Long Trade Plan:**
        *   Entry: Suggest entry near the current price.
        *   Take Profit: $[Current Price + (2 * Suggested Stop-Loss Distance)]
        *   Stop Loss: $[Current Price - Suggested Stop-Loss Distance]
    *   **Short Trade Plan:**
        *   Entry: Suggest entry near the current price.
        *   Take Profit: $[Current Price - (2 * Suggested Stop-Loss Distance)]
        *   Stop Loss: $[Current Price + Suggested Stop-Loss Distance]
    
    **Key Data Points:**
    *   **Trend:** [Extract the 'Conclusion' from the Trend Analysis section of the technical report.]
    *   **Momentum:** [Extract the 'Conclusion' from the Momentum Analysis section.]
    *   **Volume:** [Extract the 'Conclusion' from the Volume Analysis section (e.g., Above Average).]
    
    **Risks:**
    - [A bullet point list of key immediate risks to consider, based on all reports (e.g., Overbought RSI, high valuation, negative news).]
    ---

summarize_findings:
  description: >
    Review the collection of individual stock analysis reports provided in the context.
    The user's original request was: '{query}'.
    Your task is to act as a Lead Communicator and write a final, top-level executive summary for the user.
  expected_output: >
    A final, user-friendly executive summary that directly answers the user's query and introduces the detailed reports.